import '../styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Lydia Lenk | webdeveloper</title>
        <meta
          property="og:title"
          content="Lydia Lenk | webdeveloper"
          key="title"
        />
        <meta name="description" content="Generated by create next app" />
        <meta
          property="og:description"
          content="Generated by create next app"
          key="description"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}
export default MyApp;
