import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import Footer from '../components/Footer';
import Header from '../components/Header';
import TextSections from '../components/TextSections';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Lydia Lenk | webdeveloper</title>
        <meta
          property="og:title"
          content="Lydia Lenk | webdeveloper"
          key="title"
        />
        <meta name="description" content="Generated by create next app" />
        <meta
          property="og:description"
          content="Generated by create next app"
          key="description"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <section className={styles.introduction}>
          <h2 className={styles.title}>Lydia Lenk</h2>
          <h1>
            <span className={styles.span}>web</span>developer
          </h1>
        </section>
        <TextSections />
        <a
          href="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
          target="_blank"
          rel="noopener noreferrer"
        >
          Don&apos;t click me.
        </a>
      </main>
      <Footer />
    </>
  );
};

export default Home;
